services:
  postgreSQL:
    image: postgres:17.2
    environment: #изменить
      POSTGRES_USER: "tester"
      POSTGRES_PASSWORD: "testPassword1"
    container_name: postrges
    ports:
      - 5432:5432
    restart: always
    volumes:
      - /home/igor/CourseWork/db/data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_table.sql
    networks:
      CourseWorkNet:
        ipv4_address: 172.16.1.4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tester -d tester"] #изменить имя DB
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  server:
    build: 
      context: server/
      args:
        UID: ${UID}
        GID: ${GID}
    container_name: server
    ports:
      - 7432:7432
    restart: always
    env_file:
      - .env
    volumes:
      - ~/CourseWork/configuration:/configuration
    networks:
      CourseWorkNet:
        ipv4_address: 172.16.1.5
    logging:
      driver: "json-file"
      options:
        max-size: 100m
        max-file: "1"
    #healthcheck:
    links:
    - postgreSQL

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: always
    user: "0:0"
    environment:
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: 172.16.1.4:5432
      GF_DATABASE_NAME: my_grafana_db
      GF_DATABASE_USER: my_grafana_user
      GF_DATABASE_PASSWORD: my_grafana_pwd
      GF_DATABASE_SSL_MODE: disable
    ports:
     - 3000:3000
    depends_on:
      - postgreSQL
    volumes:
      - grafana:/var/lib/postgresql/data
    networks:
      CourseWorkNet:
        ipv4_address: 172.16.1.6
      
volumes:
  db:
    driver: local
  postgreSQL:
    driver: local
  grafana:
    driver: local

networks:
  CourseWorkNet:
    driver: bridge
    ipam:
      config:
        - subnet: "172.16.0.0/16"
